### ISSUE TITLE
Complete removal of `/info entity` and it's correspondent carpet functionality

### ISSUE THREAD

**Issue by altrisi** [gnembon/fabric-carpet#1033]
`/info entity` hasn't been a thing since 1.13 days...

When the command was ported in 9cf9928bbd918c0b130b080d037b78aaaf5b102e, the EntityInfo class already complained that the `/data get entity` command should be used instead.

Right now it's just being there in the command to announce it isn't a thing, spamming the message once per entity if you provide it multiple entities in the selector, or spamming your chat if you are trying to decorate with yellow carpets and have the `carpets` and `commandInfo` rules enabled (which I must say is quite annoying).

Is there anything blocking its removal? Related: It has been recently ported from 1.13 to a Carpet extension, Carpet TIS Addition.

**Comment by gnembon** [comment]
I don't believe there is anything blocking it at this point.

**Comment by Fallen-Breath** [comment]
The reasons why I ported `/info entity` to 1.14+ are:

- `/info entity` provides a much more human friendly readable information about the target entities than `/data get entity`
- `/info entity` is able to show things that would not be serialized into nbt
- `/data get entity` might lose accuracy during data conversion to nbt. e.g. item stack with count > 127

But ye, it's ok if fabric carpet is decided to completely remove `/info entity` since it's no longer beening maintaining here

**Comment by altrisi** [comment]
Yeah, makes sense that it can be useful in some cases (else you wouldn't have ported it lol), but given it's not really provided anymore in Carpet, other than the messages that it isn't provided, I thought why have the code around (here) causing those minor annoyances (mostly the carpet placement spam, that hasn't been ported and was actually removed from 1.13 Carpet, but also the autocomplete for a command that doesn't work).
