### ISSUE TITLE
[Bug][Bots] Players spawned in survival while spawning player is in spectator, spawn flying in survival

### ISSUE THREAD

**Issue by Crec0** [gnembon/fabric-carpet#1263]
Basically the title.

## Steps to reproduce
- Run `/player Steve spawn at x y z facing u v in minecraft:overworld in survival`, y being any y level mid air, while in spectator, 

## Expectation
- Steve should fall on ground since its in survival mode

## Observation
- Steve will spawn flying midair in survival mode. If you do `/player Steve move forward` they walk forward mid air

## Version info
- Game: 1.17.1
- Carpet 1.4.56

**Comment by Ghoulboy78** [comment]
https://github.com/gnembon/fabric-carpet/blob/4a1a710eb088c2cceef7d7951a66c47857a110e4/src/main/java/carpet/commands/PlayerCommand.java#L281-L287
This is the problematic line of code

**Comment by Ghoulboy78** [comment]
More info on the bug: It only occurs when the summoning player is actually flying (so doesn't work when walking in creative mode), and ye that's basically it.
Tbh it's an understandable mistake, and the fix is just as easy. I basically check if the game mode we're spawning the player in is survival-like and if so set flying abilities to false.
