### ISSUE TITLE
Named villagers lose name after tracking breeding or iron golem spawning

### ISSUE THREAD

**Issue by manchesterjm** [gnembon/fabric-carpet#1474]
Using /track villager iron_golem_spawning or /track villager breeding deletes custom names given to villagers when /track villager clear is used.

**Comment by ch-yx** [comment]
This is a known bug.....

**Comment by manchesterjm** [comment]
Thanks for the info... I did a search on previous bug reports and didn't find it.

**Comment by altrisi** [comment]
The `/track` command is a bit legacy, all of it's functionality has been moved to the `ai_tracker` app (`/script load ai_tracker`), that doesn't modify the entity names. I believe the only reason `/track` is still around is because you need carpet in your client to be able to see the texts in the app version.
