### ISSUE TITLE
stackableShulkerBoxes not removing NBT data

### ISSUE THREAD

**Issue by MANMIK1** [gnembon/fabric-carpet#1587]
If you place a shulker box and then mine it, it won't remove the NBT data, making it unstackable with new boxes you craft

It's been a while since I noticed this problem, I tried to download latest versions but nothing works

**Comment by altrisi** [comment]
Found the cause of the issue.

**Comment by James103** [comment]
The commit you pushed to fix this issue only accounts for the default shulker box (`minecraft:shulker_box`), not its color variations which have different IDs (`minecraft:white_shulker_box` and similar for the other 15 colors). Is this issue already fixed for colored shulker boxes or is there still a problem with them?

**Comment by altrisi** [comment]
Oof, forgot about those

**Comment by altrisi** [comment]
Why did Mojang add that if the id is already in the item itself???

**Comment by altrisi** [comment]
Tested with colored boxes: It uses the same `minecraft:shulker_box` identifier, so it works too.

**Comment by MANMIK1** [comment]
Sorry but this is my first time reporting a bug and I'm not quite sure what I'm supposed to do with the fix you sent in here. Could you explain it real quick?

**Comment by altrisi** [comment]
It means it'll be fixed in next Carpet version, sadly it will be for snapshots. Just got told that Crec0 made a carpet script to fix it, you can use it while this isn't in a release: https://cdn.discordapp.com/attachments/819989208147820544/1028900274754048030/fixboxes.sc (put the file in your world's `scripts` folder, and either restart/reload or do `/script load fitboxes`)
