### ISSUE TITLE
Tick warp should work in combination with tick freeze

### ISSUE THREAD

**Issue by PhoenixIV** [gnembon/fabric-carpet#1616]
_Thank you for providing such a nice basis for experiments!_

Tick warp only works when ticks are not frozen. I would like to be able to use it to fast-forward x ticks while in the freeze state!

**Comment by CommandLeo** [comment]
Use `/tick step`

**Comment by PhoenixIV** [comment]
Thanks for your suggestion. Tick step is running the game at normal speed. I am looking for warp.

**Comment by altrisi** [comment]
I think the real issue here is `/tick warp` counting frozen ticks. I'll try to fix that for the next version so these don't count, and then you should be able to freeze, start a warp and then step should warp for these ticks.

For now though, you could probably make a script to add a command to unfreeze the game, immediately start a tick warp and freeze the game again immediately after.

**Comment by altrisi** [comment]
Made one:

`frozenwarp.sc`:
```js
__config() -> {
  'commands' -> {
  	'<ticks>' -> 'warp'
  },
  'arguments' -> {
    'ticks' -> {
	  'type' -> 'int',
	  'suggest' -> [3600, 72000]
	}
  }
};

warp(ticks) -> (
  run('tick freeze off');
  print(run('tick warp ' + ticks + ' tick freeze'):1:0);
);
```
And then `/frozenwarp 3600` should unfreeze the game, warp it for 3600 ticks and freeze it back.

**Comment by PhoenixIV** [comment]
>  and then step should warp for these ticks

You mean one would have to execute `/tick step` additionally? That does not sound useful. I guess I misunderstand?

> Made one:

Nice.

**Comment by altrisi** [comment]
Going to close this as `/tick` is now a vanilla command.
