### ISSUE TITLE
Mod incompatability [Harder Farther] 

### ISSUE THREAD

**Issue by arazadaz** [gnembon/fabric-carpet#1748]
This is actually a mod I manage, so if you think something need's to be done on my end, just let me know. Anyways, this mod crashes with yours. It seems to conflict with my conditional mixin that prevents an entity from spawning if they don't meet the condition.

Here's the crash report: https://pastebin.com/8uT0JCeG

**Comment by altrisi** [comment]
I think it's because both mods are redirecting the same method in `SpawnHelper`, `spawnEntityAndPassengers` (mojmap: `NaturalSpawner.addFreshEntityWithPassengers`), and two redirects for the same can't exist at the same time.

So for them to be compatible one would need to be changed, or maybe one of Mixin Extra's alternative redirector (WrapWithCondition) could make it work, but gnembon doesn't want Carpet to use libraries too much if possible I think.

Here's the mixin in Carpet:
https://github.com/gnembon/fabric-carpet/blob/22f31a7b51eec55332b49d07dc27ab8ad08fecba/src/main/java/carpet/mixins/NaturalSpawnerMixin.java#L153-L175

I personally don't know much about this part of the code, so I wouldn't know how to adapt it, or even if it would be possible to from Carpet. This code seems to be managing our `/spawn` reporting and mocking, and something for the `lagFreeSpawning` rule.

**Comment by arazadaz** [comment]
I don't think Conditionality would work, but regardless, I overhauled the respective section of my code and it is now compatible.
