### ISSUE TITLE
"tick freeze" command seems doesn't stop the 15s time counting of the nether portal loader

### ISSUE THREAD

**Issue by Harveykang** [gnembon/fabric-carpet#204]

**Comment by gnembon** [comment]
uuu, that's a big issue. Will need some redesign of certain things. Thanks for reporting.

**Comment by gnembon** [comment]
wrote a little app for it. Turned out with warping nether unloaded one tick shorter. Might have to do with server tasks. But with tick rate - shouldn't be an issue. Maybe its lag related (this 1 tick difference) since warping pretends to a constant lag for the server.

Can you confirm its  one tick difference, or something else.

**Comment by Harveykang** [comment]
![X CBVJX}Q5C4DB4@2@VUDCV](https://user-images.githubusercontent.com/46108547/79171216-11285600-7e24-11ea-8284-3c869097cc4f.png)
![D(IHZ~MF_MOU W57EF%JE(L](https://user-images.githubusercontent.com/46108547/79171194-01a90d00-7e24-11ea-9aba-3e3d6db2343d.png)
"tick freeze" breaks mob switch

but the issue of "tick rate" is 1 tick difference. I thought that was the same issue as "tick freeze" one, sorry about that.
