### ISSUE TITLE
Add a global config file for use by all singleplayer worlds.

### ISSUE THREAD

**Issue by chexo3** [gnembon/fabric-carpet#211]
It's a pain to turn off certain things I would rather not have available to me in a survival setting on a per-world basis. I understand the utility of a lot of these things but personally I'd rather have to force myself to do the open to lan enable cheats trick when I want to use some of these more powerful, cheaty tools.

**Comment by altrisi** [comment]
Maybe copying a [`FabricLoader#getConfigDir`](https://github.com/FabricMC/fabric-loader/blob/25c9313571e1c99597705d9ee1d1b3be1cb6e681/src/main/java/net/fabricmc/loader/FabricLoader.java#L150-L163)`/carpet/default_carpet.conf` file on world creation?

Although probably this issue is a xy about `draw`, `tick` and similar commands.
