### ISSUE TITLE
Conflict with Immersive Portals Mod

### ISSUE THREAD

**Issue by Decrepitdoors** [gnembon/fabric-carpet#242]
Seems there's a conflict here, not sure if it can be fixed but I'd love to be able to use both mods at the same time.

`[Warn] @ModifyConstant conflict. Skipping immersive_portals.mixins_ma.json:block_manipulation/MixinServerPlayerInteractionManager->@ModifyConstant::modifyBreakBlockRangeSquare(D)D with priority 1000, already redirected by carpet.mixins.json:ServerPlayerInteractionManager_antiCheatMixin->@ModifyConstant::addDistance(D)D with priority 69420.`

**Comment by Ghoulboy78** [comment]
Looking through the code, I suppose it's possible to change that value, but I cannot say for certain what effect that would have, what it would break

**Comment by Ghoulboy78** [comment]
yeah, I tried modifying it, and then I coudlnt get it to open up. Maybe there was something wrong with the way I installed the mod (I doubt it, cos the instructions are pretty clear) but jic, just tell me how you installed the mod.

**Comment by Decrepitdoors** [comment]
Damn, I was hoping it would be an easy fix, I had it installed on my server, just putting the mod into the mods folder. I don't see how it could install wrong, but maybe. 

I was trying out other mods and forgot to remove immersiveportals and it threw a different conflict error with carpet:
`[Warn] Method overwrite conflict for getTicketManager in immersive_portals.mixins.json:MixinServerChunkManager, previously written by carpet.mixins.ServerChunkManagerMixin. Skipping method..`

So I'm thinking it's a bigger issue than I first expected. I'm just using carpet instead for now as it gives me more functionality. I might swap it out in the future once I have some more farms situated and just want the visual mods instead.

**Comment by gnembon** [comment]
there is something wrong with the priority system. higher number should mean it would apply later, not earlier. I already modified that mixin to be 69420, and 'can' fail, since its not crucial for carpet. I can check with fabric/mixin gurus to confirm how this work/should work. In the case of player reach mixin from carpet should come later and should be able to fail.
Regarding getTicketManager - I guess all these should get their own names for each mod - should be easily fixable. Understandable that other mods would like to get access to the same things. Will rename.

**Comment by Decrepitdoors** [comment]
Hmm maybe it's backwards and uses 1 as highest priority, this is all very good to hear otherwise, I look forward to an updated file to test with immp, when you have it done.

**Comment by Decrepitdoors** [comment]
I just downloaded 20w18a carpet to check compatibility, I've been playing with immersive portals for the past week, and I'm happy to say all seems to be compatible now. :D
