### ISSUE TITLE
[1.16+ Suggestion] Make redstone only visually connect to powerable blocks

### ISSUE THREAD

**Issue by muzikbike** [gnembon/fabric-carpet#263]
Based on a rejected bug tracker report. Placed redstone wire should update its block states to only point in the direction of blocks it actually is capable of powering, to better match up with the logic behind it. Would only affect redstone dots and straight lines.

Single redstone dots: would appear as dots if placed isolated, would point in a single direction if next to a solid block that can carry power, would appear as a straight line or L shape depending on configuration if pointing into two blocks that can carry power, a T shape if there are three blocks, and a + shape for 4 blocks.

Long lines of redstone wire: would appear half the length (possible with new 20w18a blockstates) if not pointing into a block that can carry power, or would appear at the current full length if it is pointing into such a block.

The bug report has some visual examples which should make this easier to understand: https://bugs.mojang.com/browse/MC-181764

**Comment by Ghoulboy78** [comment]
Not necessarily, as there could be, say, a BUD which receives the update in another direction, and not to mention that half a redstone wire would look pretty ugly.
Also, how would the redstone dust know that there is something on the other side of the block which has to be powered without doing a ton of extra checks? This would be very laggy, and moving blocks next to redstone would be impossible.
And not to mention, I don't think this is something appropriate for the carpet mod per se, as it is a mod for gameplay optimizations, not really visual ones. Even the smoothClientAnimations is there so that you can actually see a fast moving contraption without getting dizzy and trying to figure out where the hell your pistons are.

**Comment by Ghoulboy78** [comment]
Edit, I re read, and some of what I said is nonsense, but the rest isnt. BUt on the other hand, this would mean implementing custom blockstates, and the game wouldn't be compatible with vanilla anymore
