### ISSUE TITLE
Ghost piston heads

### ISSUE THREAD

**Issue by Bigrin** [gnembon/fabric-carpet#279]
![2020-05-14_17 30 58](https://user-images.githubusercontent.com/52777811/81906807-2b637880-960a-11ea-849f-8ab8781c4037.png)
Ghost-block piston heads are created by immediately powering a piston after rotating it. (rotators enabled).
Using version 20w20a.

**Comment by gnembon** [comment]
well, that's not rotating block that causes it but the piston behaviour itself. If you would fix it I would need to fix piston bedrock breaking as is stands in the game.

This is exactly what happens with bedrock breaking scenarios where one piston is replaced with another - here it is just rotated, instead of replaced.

**Comment by Bigrin** [comment]
Thanks for clarifying
