### ISSUE TITLE
Porting to Forge?

### ISSUE THREAD

**Issue by James103** [gnembon/fabric-carpet#306]
I understand if you don't want to do it, but porting this mod to Forge will allow many more people to use this mod for modern Minecraft versions, and also allow this mod to be used together with more mods in general.

**Comment by gnembon** [comment]
problem with forge is that its not a vanilla game, but a game with certain treatment already applied to it. Its not uncommon for forge to fix bugs prior to mojang, that some technical players (ab)use. Plus fabric allows to stay on top of snapshots pretty much right as they come out.

**Comment by BraveCaperCat2** [comment]
And nobody needs to use features such as moveable tile entities (which they could be doing in bedrock preview which all java players should have by now) or increased push limits in snapshots.
and if those technical players use those bugs - why should they be using this mod anyway?
they'd probably be using "redstone run fast" mods more, which use both fabric and forge - plus there is a much bigger forge community than fabric community (citation needed) and even though (curse)forge doesn't really support the modders, there are way many more out there which have used forge since MC 1.7.10 days. (me partly included, as i've used that MC version before)

**Comment by altrisi** [comment]
However, porting to snapshots means that you follow the changes as they're done to the game so it's way easier to update than doing the whole update at once.

Not only that, Carpet isn't all about MBE and push limit, it has a lot of features to run testing, such as hopper counters, speeding up time or fake players. That's very helpful, and when a new feature just dropped it's really nice to have, and judging by how there's quite a few downloads of those versions, many people use it.

Forge does (or at least has in the past) actually change some behaviour, and many people using Carpet rely on behaviour being precise, which fabric gives by not doing anything by default (and Carpet doesn't even need Fabric API). Not necessarily to abuse bugs (though sometimes), but to make sure stuff works without mods too or to exploit features to their limit without unwillingly relying on some limit by some change somewhere.

Porting to Forge also isn't "just porting it". It takes quite some effort. It's simply not something we are motivated to do (I don't really use forge, definitely not where I'd need Carpet, and I doubt gnembon does either), and given we do this on our free time and for fun, well, we simply don't port it.

Some of Carpet's features are on forge in some other mod though from what I know btw, you may find the ones you want to use out there.

BTW, please don't post to an issue closed 3 years ago. At that point is likely better to open a new one (or ask in the discord!).
Thanks!

**Comment by BraveCaperCat2** [comment]
> However, porting to snapshots means that you follow the changes as they're done to the game so it's way easier to update than doing the whole update at once.
> 
> Not only that, Carpet isn't all about MBE and push limit, it has a lot of features to run testing, such as hopper counters, speeding up time or fake players. That's very helpful, and when a new feature just dropped it's really nice to have, and judging by how there's quite a few downloads of those versions, many people use it.
> 
> Forge does (or at least has in the past) actually change some behaviour, and many people using Carpet rely on behaviour being precise, which fabric gives by not doing anything by default (and Carpet doesn't even need Fabric API). Not necessarily to abuse bugs (though sometimes), but to make sure stuff works without mods too or to exploit features to their limit without unwillingly relying on some limit by some change somewhere.
> 
> Porting to Forge also isn't "just porting it". It takes quite some effort. It's simply not something we are motivated to do (I don't really use forge, definitely not where I'd need Carpet, and I doubt gnembon does either), and given we do this on our free time and for fun, well, we simply don't port it.
> 
> Some of Carpet's features are on forge in some other mod though from what I know btw, you may find the ones you want to use out there.
> 
> BTW, please don't post to an issue closed 3 years ago. At that point is likely better to open a new one (or ask in the discord!). Thanks!

1. Yes i get your point with the snapshots - but the players don't necessarily need them.
2. Those are the features i use (other than the /tick warp command, it makes my small little note block thingy play ALL the note blocks at once)
3. WAIT - your mod doesn't use fabric API???? does that mean that porting to forge is as simple as changing the dependancy to being forge instead of fabric??? (i was reading your part by part response 1 part at a time, then writing my response to your response)
4.  There are many uses of forge out in the wild (not nessecarilly everywhere but outside this webpage there are forge mods crammed into the smallest spaces) - for example, some mods such as [BuildCraft](mod-buildcraft.com), [RailCraft](curseforge.com/minecraft/mc-mods/railcraft) and many more (I'll add [TekTopia](https://sites.google.com/view/tektopia), even though it isn't developed anymore) require forge since they haven't updated to versions supported by fabric (or Quilt, a fork of farbric, in the case of [BuildCraft](mod-buildcraft.com)) All of which are for 1.12.2 and [BuildCraft](mod-buildcraft.com) and [RailCraft](curseforge.com/minecraft/mc-mods/railcraft) support eariler versions such as 1.7.10.
5. Found it - it's right [Here - It's called Forged Carpet](https://www.curseforge.com/minecraft/mc-mods/forgedcarpet) - Altough it's only for 1.12.2 (because fabric doesn't support, as said above)
6. I was going to open a new issue, but then i thought you (or someone else) would of closed it because it is a duplicate of this - something along the lines of "Duplicate of #306" - Also i don't use discord.
