### ISSUE TITLE
Default carpet.conf when creating new world

### ISSUE THREAD

**Issue by TrueCP6** [gnembon/fabric-carpet#356]
Having a carpet.conf file in `.minecraft/config` that gets copied to the world folder when a new world is created would prevent you from having to change the same settings every time you create a new world (or having to copy carpet.conf from another world).

**Comment by gnembon** [comment]
well, default carpet.conf is an empty file. If you change some settings permanently, the carpet.conf should be created. 

Don't understand what is the problem here.

**Comment by TrueCP6** [comment]
What I meant was that you could have settings that automatically apply as default to a world when it is first created.

For example you could define `carpets` as `true` in a file, and so when you make a new world, `carpets` will be enabled without having to do anything or change any settings. It would just be a quality of life feature.

**Comment by supersaiyansubtlety** [comment]
I would also greatly appreciate this feature.

**Comment by MatthewOverall** [comment]
I agree, this would be beneficial along with default scripts.

**Comment by altrisi** [comment]
Maybe copying a [`FabricLoader#getConfigDir`](https://github.com/FabricMC/fabric-loader/blob/25c9313571e1c99597705d9ee1d1b3be1cb6e681/src/main/java/net/fabricmc/loader/FabricLoader.java#L150-L163)`/carpet/default_carpet.conf` file on world creation (to state clearly that it is only a default, not global config, and the `carpet` suffix to allow extension's configs too and because it's the actual file name)?

Relates directly to #211.
