### ISSUE TITLE
/player (name) use continuous

### ISSUE THREAD

**Issue by SouthernPixel** [gnembon/fabric-carpet#378]
Command does not work with food in the offhand and attacking. It looks like its using it because the food flashes like its being used but its not. It will occasionally eat but not reliably. I tried doing "/player (my name) use continuous" and "/player (my name) attack interval 13 at a farm and i die of starvation eventhough its suppose to eat coninuously while attacking.

**Comment by Ghoulboy78** [comment]
What carpet and game version?

**Comment by SouthernPixel** [comment]
well the server that I play on is 1.15.2 and it should be the latest version of Carpet 1.15

**Comment by gnembon** [comment]
well, due to the client not knowing that use are eating, breaking the action, it doesn't work on actual players. Think of it as a fast right clicker. For eating you have to keep it pressed and that's what not gonna happen. If you are on a server you should be able to set your actions and then shadow yourself, and after being kicked, your fake player should be able to eat.
