### ISSUE TITLE
[Minor Enhancement] chunk_display built-in app almost unusable without Carpet in the client

### ISSUE THREAD

**Issue by altrisi** [gnembon/fabric-carpet#396]
While the chunk_display is now extremely useful to view those when using Carpet in the client, while I was preparing another issue related to chunk loading I will post later, and testing in the last snapshot version to make sure it wasn't fixed, where I don't have Carpet in the client, I found that the chunk_display app is now almost unusable without the client, since the particles are almost invisible in some positions and they also don't always render, and while moving they all just mix up.
Maybe there could be a check to see if the player has Carpet client (would require a method/query in the API, that may be useful for other apps too) and display a different display without the client (like the old chunk/load display that made a floor with the display, for example).
If you go above the display it's slightly better.

Video: https://streamable.com/uz63lw
Only using Carpet 1.4.4 in 20w30a in loader 0.9.0 build 204.

Edit: With Minor I refer to priority (since almost no one uses the display without the Client), not to complexity.

**Comment by Ghoulboy78** [comment]
Ig I could add a way to check for the carpet client, but do u mind writing the extra scarpet stuff urself?

**Comment by Ghoulboy78** [comment]
yeah... idk how to do, plus im 77.2% certain gnembon won't like it... tell me if I'm wrong, prof G.

**Comment by gnembon** [comment]
well, that's unfortunately how it is supposed to be. With a typical usage of 32 vd, this gives 4000 chunks to update every tick. while probing is still ok (getting typically 20-30 mspt (reasonable) that gives potentially thousands of packets per tick just for the display. Therefore chunk_display only updates squares every 100+random ticks or when they change. This makes so that particles are sent every ~7 seconds, meaning they will already discipate.

Having said that - I tweaked display of particle lines and cubes for small lengths and exposed `global_update_interval` that can be tweaked by the players I guess. that makes the vanilla chunk display more usable I guess.

https://github.com/gnembon/fabric-carpet/commit/7a1e05cfa16a5675e38141469dd5e439f696c69d
