### ISSUE TITLE
issues with ai_tracker and fabulous graphics

### ISSUE THREAD

**Issue by bitslinger70** [gnembon/fabric-carpet#420]
video settings graphics option on Fast and Fancy are fine but when I set it to Fabulous the ai_tracker visuals can only be seen briefly when in just the right position.

**Comment by altrisi** [comment]
The problem isn't specifically with `ai_tracker`, but with the general Shapes API. It used to work in previous versions (1.16.1, with fabulous graphics on).

- When running fabulous, you aren't able to see Carpet shapes (with the mod in the client-side)
- In lower graphical settings, Carpet shapes are rendered normally (with the mod in the client-side)

Without the server seeing Carpet in the client:
- Shape particles are generated once per shape, and therefore the `duration` argument is ignored (doesn't affect built-in apps, since they send new shapes regularly, but may affect custom apps), but the particles are rendered correctly in fabulous

**Comment by gnembon** [comment]
lol 420
