### ISSUE TITLE
[Suggestion] Lag Tester

### ISSUE THREAD

**Issue by Kallefinn** [gnembon/fabric-carpet#465]
Im not sure if there  is already a practical way of testing contraptions under laggy conditions but it would be helpful to be able to perform a tick warp under extreme conditions to make sure it is lag proof. So i would propose the addition of a tick warp with lag spikes to test for extreme casses. If there already is a way or if it isnt possible please let me know.

**Comment by Ghoulboy78** [comment]
But that is system specific, so you can't do that.

**Comment by Ghoulboy78** [comment]
like it's different from pc to pc

**Comment by altrisi** [comment]
Almost sure that `Thread.sleep(5000)` would make any system generate a lag spike.
But of course generating a lag spike under a tick warp would basically slow down the ticks, so it wouldn't be a tick warp any more.
It would be about finding what does the game consider a "lag spike" and force that state instead in order to keep the game fast.

**Comment by altrisi** [comment]
Actually, the 1.12 version of Carpet uses exactly that at [LagSpikeHelper.java#L28](https://github.com/gnembon/carpetmod112/blob/419d14d6d5553828ac354bc89e6b05ceab73bf92/carpetmodSrc/carpet/helpers/LagSpikeHelper.java#L28), but once again that does literally lag the game for that time, making the tick warp ticks really slow.

**Comment by gnembon** [comment]
you should be able to have a script doing lag exactly how you would wanted from it. By using entity events, using `on_tick` or by using `schedule` you can 'add stress' in various points of the game tick.
