### ISSUE TITLE
Spawn reports to omit locations for non-op survival players

### ISSUE THREAD

**Issue by meza** [gnembon/fabric-carpet#485]
Placing carpets is a nice way to give the survival players some neat functionality but reporting where the mobs are removes the element of adventure and exploration. It would be neat to be able to restrict that to ops or to turn the coords displays off completely.

Alternatively disabling a specific carpet's functionality could be cool

**Comment by altrisi** [comment]
About the spawn command displaying coordinates: I also think it would be nice to have those separate or with a permission option, but it has always been this way and I don't think it's that big of a deal.

About disabling Carpet functionalities: All Carpet features can be disabled (if you lock the config file, they will actually all be disabled by default), because they come with their own [Carpet rule](https://github.com/gnembon/fabric-carpet/wiki/Current-Available-Settings).
For instance, the `/spawn` command can be disabled with `/carpet (setDefault) commandSpawn false`, but that would also disable the respective carpet for it.

**Comment by meza** [comment]
> For instance, the `/spawn` command can be disabled with `/carpet (setDefault) commandSpawn false`, but that would also disable the respective carpet for it.

Or have separate `carpet*` settings for each carpet. That would be cool too.

**Comment by altrisi** [comment]
Actually, doesn't having the command only available to ops (rule to `ops`, or any permission level) allow using carpets to everyone but commands only to ops?

**Comment by gnembon** [comment]
spawn command now defaults to ops, so that's covered I guess. Not because of that, but the ability to affect mobcaps and spawn rates.

Carpets when enabled will only work on 'enabled' features, so don't see this being an issue.
