### ISSUE TITLE
[Suggestion] Bindable Crawling

### ISSUE THREAD

**Issue by VampireMonkey** [gnembon/fabric-carpet#489]
Crawling is useful but a bit tedious that you need something to trigger it, it would be cool if it was just a button press to activate like going prone in other games.

**Comment by altrisi** [comment]
Not sure if suited to Carpet since it modifies and is required in the client-side.
Carpet is thought to only slightly modify the server while letting vanilla client join and have the same features, but this contains a keybind that vanilla players couldn't use without modifying their client.
I think this may be better suited to either carpet-extra or another mod (personal opinion).

**Comment by Ghoulboy78** [comment]
I agree. Maybe you should ask masa, in tweakeroo maybe?

**Comment by altrisi** [comment]
There is actually already a mod to do that: https://www.curseforge.com/minecraft/mc-mods/crawl (compatibility not tested)

It is, of course required to be in both sides, server and client.

**Comment by gnembon** [comment]
outside of scope. Good suggestion though.
