### ISSUE TITLE
Bukkit For Fabric (Mod) Incompatibility (1.16.1<)

### ISSUE THREAD

**Issue by RichardIsSoarx** [gnembon/fabric-carpet#499]
Every time I attempt to load CarpetMod with this Project it gives me these mixin errors messages then proceeds to crash. Here is a link to the Bukkit For Fabric project to get some background (https://github.com/BukkitFabric/bukkit4fabric). The mod worked fine up until 1.16.2 something after had changed. I have attached a error log below trying multiple versions of CarpetMod in the latest 1.16.3 version. 
[CarpetModGnembom.txt](https://github.com/gnembon/fabric-carpet/files/5380058/CarpetModGnembom.txt)

**Comment by altrisi** [comment]
This is probably due to the fact that their way of making their mod work is to basically override lots of methods, making it easy for a mixin from another mod (Carpet, in this case) to fail hard due to not being able to find what it was supposed to be there.

Fixing it from here would probably require lots of workarounds just for a single mod, and that's probably not going to happen for many reasons, mainly because Carpet tries to not add (many) workarounds for compatibility with other mods to try to keep it easier. It may be a better idea to ask them to fix it if they want to, and hopefully they will try to use less overwrites in the future to prevent compatibility issues.
