### ISSUE TITLE
[Suggestion] Modify or remove `/player shadow`

### ISSUE THREAD

**Issue by ExaInsanity** [gnembon/fabric-carpet#512]
Most `/player` subcommands are great and very useful.
`/player shadow` not so much. While I couldn't think of any positive uses for the command, it has a lot of destructive use cases - steal other player's inventories without any effort whatsoever.
You can only disable `/player` entirely - which means if you want to disable shadow, you also have to disable spawn etc., which are all useful commands - therefore I suggest either adding a separate toggle for shadow or removing it altogether.

**Comment by altrisi** [comment]
In theory, only OP players can shadow _other_ players since 19a01bee1be79e9ddc8f9056bc30dd9b9d15c02b (around 1.3.20). If not, that's probably a bug.

Shadowing is useful, for example, when you want to get yourself AFK instead of making a bot, without leaving your computer open (either because of xp, inventory, tools or feeling having extra bots to be cheaty).

I don't think that granularity would be that useful while having the OP check.

**Comment by gnembon** [comment]
yeah, you might need to update your carpet version. If you trust players with OP priviledges, there are other easier ways to generate items, than stealing from other players. Please provide details how this happen - maybe its just a matter of updating your carpet version.

**Comment by ExaInsanity** [comment]
Seems as though updating carpet fixed it for carpet-only setups, for some weird reason it still works on my production server (which runs a shadow-deprived version for now), but no matter what mod i remove the shadow check works again... looks as though this isnt necessarily a carpet issue
