### ISSUE TITLE
Duplicated villager tracking data shows on Orderly mod

### ISSUE THREAD

**Issue by NightOps007** [gnembon/fabric-carpet#521]
I think this is more of an issue with orderly than carpet, but posting here as well since there may be solution from this end also. See linked issue for more info. [Orderly mod issue#37](https://github.com/UpcraftLP/Orderly/issues/37)

**Comment by altrisi** [comment]
Found the "issue". This is because the `track` command works by changing the entity name to those values, and it seems that Orderly basically displays the name of the entity in their popup. It probably won't be fixed from here.

It is recommended to use the `ai_tracker` built-in Scarpet app instead since it has more features and is more configurable (do `/script load ai_tracker`), and doesn't modify the entity name.

**Comment by gnembon** [comment]
track will eventually be phased out and merged into the app, so that's about that.
