### ISSUE TITLE
Maybe also a way to specify command permissions: you can pass a numeric permission level

### ISSUE THREAD

**Issue by gnembon** [gnembon/fabric-carpet#542]
Maybe also a way to specify command permissions: you can pass a numeric permission level and then you have a function to change that level from the code, so it hides the command like it does with other Carpet commands instead of having the command always visible, then checking, then saying `Sorry, you no good`. (for example to use with Scarpet Rules or to allow ops to change perms of an app on the fly)

_Originally posted by @altrisi in https://github.com/gnembon/fabric-carpet/issues/221#issuecomment-721001680_

**Comment by altrisi** [comment]
Another way now that I'm seeing how does Brigadier check that:

Giving a reference to a variable (maybe even a "built-in variable"?) (or a lambda or something, like in Scarpet rules to directly check the rule value) and just evaluate from there whenever the command runs.
Something like the suggester, but to get a string to check against standard Carpet perms instead of suggesting.
```py
       'command_perm' -> _(args) -> (
          if(global_isEnabled,
            global_permission;
          ,
            'ops';
       ),
```
This could return a boolean (so it could have granular permissions completely decided by the app in a specific moment, problem: booleans are = 1), or another of the compatible Carpet permissions (0-4, `ops`).
Maybe without `args`, since that would probably be too difficult if at all possible, but probably send the player there.

**Comment by altrisi** [comment]
I'd say this blocks #553 (to prevent non-ops just starting to draw shapes without having the right permissions).

**Comment by gnembon** [comment]
Lambda would be ideal - the problem is that __config is NOT executed again for player apps when copied from the parent app, meaning the functions may be referencing the incorrect module (parent module). I am not 100% certain about it though - might all be just fine. It would be ideal to specify callback accepting player argument (or null for server calls).
