### ISSUE TITLE
chainStone command not showing up

### ISSUE THREAD

**Issue by Premtage** [gnembon/fabric-carpet#543]
When I type /carpet chainStone in chat it just says that it doesn't recognize the command, was the command removed?

**Comment by James103** [comment]
What version of Carpet Mod and Minecraft are you using?

**Comment by Premtage** [comment]
> What version of Carpet Mod and Minecraft are you using?

1.16.3 and I'm using the 1.16.4 version of carpet mod since gnembon said it should work okay

**Comment by altrisi** [comment]
It says that the entire command doesn't exist? Or just the rule?

If it's the latest, then you must be running an old version of Carpet, get the latest release [here](https://github.com/gnembon/fabric-carpet/releases) (the one that says for 1.16.4, since you are using 1.16.x).

However, if it's the first one, then either:
- Carpet didn't load: Check you are running Fabric Loader in the server (client if singleplayer) and that Carpet is in your `mods` folder
- You have locked your configuration file: Check that the `carpet.conf` file in your world folder doesn't have `locked` as the first line

After checking those, the `/carpet chainStone` command should show the information about that rule and allow you to toggle it.

**Comment by Premtage** [comment]
im using the 1.16.3 version of Minecraft and all the other commands work just fine, you may have misunderstood me I downloaded the latest version of carpet mod that works for 1.16.3

**Comment by altrisi** [comment]
Almost sure you are using 1.4.12 (the release just before `chainStone` was added, explicitly marked for 1.16.3 since .4 didn't exist yet), but feel free to think you are using the latest version even when you aren't.

1.4.17 (or at least 1.4.13, the first release with chainstone, or 1.4.15, last that explicitly says that should work) doesn't specify 1.16.3 in the name, but should be compatible with it according to the patch notes.

**Comment by Ghoulboy78** [comment]
How broad? Iatest means 1.4.17. No vagueness involved...

**Comment by altrisi** [comment]
"Latest" can refer to:
- Latest commit (_at date..._) (_for branch..._)
- Latest release (_at date..._)
- Latest release built against (_version..._) (_at date..._)
- Latest release that says should be compatible with (_version..._) (_at date..._)
- Latest release that should be compatible with (_version..._) (_at date..._)
- Latest release for (_version..._) (_at date..._)
- Latest version published to Curseforge (_at date..._) (they still have 1.4.12 lol)
- _And more..._

**Comment by Premtage** [comment]
i checked in my mod file and carpet is 1.14.12 i will try a newer version if the problem gets solved i will close this issue, thanks.

**Comment by Premtage** [comment]
but will the settings in the carpet.conf reset if I download a newer version?

**Comment by Premtage** [comment]
i cant find the download link lol

**Comment by altrisi** [comment]
No they won't, configs are always kept between versions, since they use the same format.
