### ISSUE TITLE
[Suggestion] Game freeze when nobody online (for server)

### ISSUE THREAD

**Issue by SpiritedAwayCN** [gnembon/fabric-carpet#550]
As mentioned in the title, could you add a new feature, that game will be frozen when every player or bot is offline ,and will run normally when anyone joins the game?

And this feature seems to only work in server env.

Thank you!

**Comment by altrisi** [comment]
This would be definitely possible with a Scarpet app instead. Check every time __on_player_disconnects if there is no one left then freeze, check __on_player_connects and if there were no one unfreeze.

**Comment by altrisi** [comment]
Something like (untested, just wrote it here):
```py
__on_player_disconnects(p,r) ->
(
  if (length(players(*) == 0, run('tick freeze'))
)

__on_player_connects(p)
(
  if (length(players(*) == 1, run('tick freeze'))
)
```

**Comment by James103** [comment]
A more general solution (where `n` is the minimum number of players that must be online) would be:
```
__on_player_disconnects(p,r) ->
(
  if (length(players(*) < n, run('tick freeze'))
)

__on_player_connects(p)
(
  if (length(players(*) >= n, run('tick freeze'))
)
```

**Comment by altrisi** [comment]
That wouldn't work. That would make it cycle randomly, since `tick freeze` would get called _every_ time a player leaves as long as there are less than n, so at n-1 it would unfreeze, n-2 freeze, etc.

Also why would you want to have the game frozen with players online?

(the solution to your case would be when `== n-1` and when `== n` I think)

**Comment by replaceitem** [comment]
@altrisi the `player(*)` only lists players in the current dimension (so it would also freeze if nobody is in overworld), instead use `player('all')` (need quotes too)
i also realized that very late that the * is only same dimension

**Comment by Ghoulboy78** [comment]
Ok, then close, yeah? also add a `__config()->{'stay_loaded'->'true'}` so it loads after server restarts.

**Comment by SpiritedAwayCN** [comment]
> Ok, then close, yeah? also add a `__config()->{'stay_loaded'->'true'}` so it loads after server restarts.

Maybe there's another problem: game should be immediately freezed when server starts completely. Otherwise, game is still running and will be freezed when a player joins the game.

**Comment by replaceitem** [comment]
For that you can just put `run('tick freeze')` inside the script, and it will be run when it loads (not inside any event)

**Comment by SpiritedAwayCN** [comment]
Thanks for everyone. This issue can be closed now.

**Comment by Ristovski** [comment]
It would appear that `run('tick freeze')` is not being run inside `__on_player_disconnects`. I have confirmed this by doing `/tick health` and comparing the output with when ticking is frozen.

Manually running `/tick freeze` from the server console, and connecting does unfreeze ticks though, so this is only something that happens when disconnecting. Any ideas?

**Comment by Ristovski** [comment]
Ok figured it out, the event gets caller before the number of players get updated, which means the following is needed:
```
__on_player_disconnects(p,r) ->
(
  if (length(player('all')) == 1, run('tick freeze'))
);
```
