### ISSUE TITLE
[bug] Crash when activating any piston

### ISSUE THREAD

**Issue by Elliott-Geoffroy** [gnembon/fabric-carpet#566]
Minecraft 1.16.4
fabric 0.20.0 1.16

carpet 1.16.4 - 1.4.17 v201111

Game crash when using any of the 2 pistons

Tell me what additional information could be usefull to you.

[crash-2020-11-20_03.15.25-server.txt](https://github.com/gnembon/fabric-carpet/files/5579403/crash-2020-11-20_03.15.25-server.txt)

**Comment by altrisi** [comment]
This is likely a conflict with another mod, since I can't reproduce it in latest commit with carpet only and the crash looks like it.

Since this is very likely a conflict with a mod that adds some behaviour to pistons (what can be moved with pistons, etc), if you know which of them could be modifying pistons, you can try (in a test world) to remove that/those and check if the issue persists. If you find a setup removing one mod where the issue doesn't exist, you will have found the cause and will be able to report it to them too (carpet doesn't usually do many specific compatibility fixes, some sometimes). But at least you need to know what mod causes the conflict, which is definitely useful.

If you are unable to figure out which mod is causing it, you could also try doing a binary search:
In a test world, never removing carpet, remove half of the mods and test if the issue persists. If not, test the other half, and remove half of the mods where issue persists. Repeat until you can reduce it to a single conflicting mod. That mod is (also) causing the issue.

**Comment by Ghoulboy78** [comment]
ye he cant do that. He has basically evry fabric mod in existance

**Comment by Ghoulboy78** [comment]
and it has nothing to do with carpet.

**Comment by altrisi** [comment]
It has technically _something_ to do with Carpet, although it's also caused by another mod. Basically there is another mod replacing where Carpet injects, so they fail hard with Carpet not finding it. If it were the other way around (Carpet injecting before that mod) the crash report would be the other way around (or no crash at all, depending in what Carpet did). Order is arbitrary, so we can't really use that.

I'm sure it will be possible to find the conflicting mod (200 mods, yeah, but could be worse).

You can also test with Mixin debug (it will be an explosion of info, but anyway) by adding the property `-Dmixin.debug=true` to your java arguments and then it would be all about finding who mixes there in the log.

**Comment by gnembon** [comment]
Why do you use

chains: Chains-Link 1.16.2-2.0.1

This mod is not coded in a 'good' way rewriting all piston code making sure that any other mod that touches pistons will fail. Use `/carpet chainStone` instead.
