### ISSUE TITLE
I can't check names for items in Scarpet

### ISSUE THREAD

**Issue by Zedespook** [gnembon/fabric-carpet#61]
Hello!

I couldn't find a way to get the name of an item which is held in the main hand. We want to use the hammer script, but with a diamond pickaxe which has the name "Hammer".

My question/issue: Can you check the name of an item and if so, how?

**Comment by gnembon** [comment]
its convoluted because item holds name, as a string nbt inside a proper item nbt, so if an item has a name, this works:
/script run get(nbt(get(get(player() ~ 'holds', 2),'display.Name')),'text')
(note double wrapping of a display.Name, as its json inside json as text
Obviously you would need to add checks whether item in hand exists (returns not null), and name exists (returns not null as well)
