### ISSUE TITLE
Can't do operations on players with leading numbers in their name

### ISSUE THREAD

**Issue by FalseMSP** [gnembon/fabric-carpet#611]
To recreate this issue run the following command on a server with Carpet:

/player 3test_ spawn

You will notice it doesn't spawn. You can try other operations and it doesn't work. I've tried scarpet things and it doesn't seem to work.

Other names that have been tested:
3volution_
3test

**Comment by James103** [comment]
Does the same thing apply for players with symbols in their name (such as underscores e.g. `_bot1234`)?

**Comment by FalseMSP** [comment]
I do not know, you can test it.

**Comment by altrisi** [comment]
I'm almost sure it's possible to spawn players whose names start with numbers, mostly because I've spawned them in the past. (Just tested it again, it's still working for me, tested both in dev env in latest commit and in a slightly outdated version in SSP)

Are you sure it's not that your server is online-mode and you are trying to spawn players that don't correspond to a Mojang account?

BTW what feedback do you get when you run those commands? Are you able to spawn players that don't start with a number?

And what Carpet version are you running (server)? 

In latest versions, by default only OP players can use the `/player` command, a server admin has to change the permissions to allow non-ops to spawn players.

Also, do you know if an error is thrown when you try to spawn them? If so, are you running other mods aside from Carpet (server)?

**Comment by FalseMSP** [comment]
okay. I just updated my carpet mod to the newest, and it seems to be working now...

**Comment by gnembon** [comment]
closing then?

**Comment by FalseMSP** [comment]
yes you can close.
