### ISSUE TITLE
[1.16.4] commandCameraMode is absent

### ISSUE THREAD

**Issue by whitebear60** [gnembon/fabric-carpet#669]
commandCameraMode commands are missing in Carpet version 1.4.20 for Minecraft 1.16.4

**Comment by altrisi** [comment]
No, it's not absent, it was removed on purpose, in favour of the F3+F4 vanilla gamemode switcher.

Since survival servers/worlds don't have access to that, at the same time an official Scarpet app that provides even better functionalities was released. You can add to your Carpet to add the behaviour back.

See instructions on how to add it in [its wiki page](https://github.com/gnembon/fabric-carpet/wiki/Cam-app).

**Comment by gnembon** [comment]
^
