### ISSUE TITLE
Make a server hosting friendly version

### ISSUE THREAD

**Issue by RangoMcRoony** [gnembon/fabric-carpet#681]
This comes after Aternos, the most used minecraft free hosting website has banned the use of all carpet mods. This was due to carpet mod allowing users to trick the server into thinking that people were online when in fact they were not using the player spawn command. 

Since carpet mod is one of the most popular mods there specifically for the optimizations it provides it is worth investing time into making a "lite" or optimization only version of carpet. Of course theres no rush. And this is an incredible time consuming task so I'm calling on coders in the community. I'm not sure where to post this and will remove this comment is this is the wrong place to post.

**Comment by gnembon** [comment]
Well, its whoever serves these servers to specify what they allow / not allow to use on their hardware. Mojang only allows their vanilla software to run on realms and they have all the reasons to do that. Provider X, that gives these for free can assume that when player are not actively playing they can stow these games making room for other clients, thus allowing them to serve more clients. 

So it all makes sense, and I am nether surprised nor worried about it. If you want to abuse aternos servers, I bet you can still do that with portal chunkloading, since its a vanilla thing, requiring little more setup than a `/player spawn` command
