### ISSUE TITLE
Hopper minecart will not drop items if it is inside a crafting table

### ISSUE THREAD

**Issue by rhinomans** [gnembon/fabric-carpet#685]
If autoCraftingTable is set to true a crafting table pressed into a hopper minecart will not drop its items into a hopper below.
setting autoCraftingTable to false the hopper minecart will drop its items.

carpet mod version 1.4.23
carpet extra mod version 1.4.23
autocraftingtable mod  version 1.4.17
minecraft 1.16.5

**Comment by altrisi** [comment]
Sounds like vanilla functionality. Doesn't the same happen if you replace the crafting table with a chest or another container?

IIRC Minecraft disables hoppers polling for entities when they have a block entity above, therefore the hopper minecart entity is ignored.

(with `autoCraftingTable`, the crafting table becomes a block entity, since it has to store its inventory etc)

**Comment by gnembon** [comment]
Yeah, that's a standard behaviour of a hopper - if there is a container above it / in it - its item pickup behaviour is different. 
That's a trade-off for enabling container properties for a block conditionally - that happens with the crafting table extension (one of many reasons its not part of any standard carpet pieces) - you get inconsistent behaviour. If crafting-crafting table was implemented as its own separate block (properly modded, not 'pretend-vanilla') than everything would be all good.

For more consistent approach, I suggest you use craftingDropper from extra
