### ISSUE TITLE
/tick freeze stops chunk loaders

### ISSUE THREAD

**Issue by felix91gr** [gnembon/fabric-carpet#707]
What the title says. The two times I've done it, my chunk loaders have been stopped. I suspect it has to do with the clock for chunk load tickets not being frozen whenever `/tick freeze` is ran.

**Comment by James103** [comment]
Have you tried checking whether the chunk loaders persist on running `/tick freeze deep`?

**Comment by altrisi** [comment]
As James103 mentioned, you need to use a deep freeze in case you want to also freeze the ticking down of loaded chunks.

That's separate on purpose because else in a default freeze any type of chunks, including the ones that players load, would never be unloaded, potentially leading to unnecessary lag or unintended behaviours.

It's actually quite simple to solve though, as mentioned, just use the `/tick freeze deep` command in cases where you need accuracy on the unloading of chunks, just note that other chunks that are loaded also will be kept loaded until the game is resumed.

**Comment by felix91gr** [comment]
Ohh, that's quite nice! Sorry for bothering you, I'll close the issue now ☺️
