### ISSUE TITLE
1.16.5 doesn't work with curren't release for 1.16.5

### ISSUE THREAD

**Issue by bloostone** [gnembon/fabric-carpet#711]
it keeps saying it needs 1.17.x

**Comment by bubble0601** [comment]
me too.
Crash report is here
https://pastebin.com/RSHjWngi

**Comment by Ghoulboy78** [comment]
It appears to be a conflict with WE actually, so update both to their respective latest versions please.

**Comment by altrisi** [comment]
@bloostone Show logs or crash report. You may have downloaded fabric-api for 1.17 instead (Carpet itself doesn't need it btw)
@bubble0601 As Ghoulboy said, yours is caused by WorldEdit 7.2.1-7.2.2 conflicting with Carpet. Either use 7.2.0 or wait for 7.2.3 to be released (or build it from their repo)
