### ISSUE TITLE
Crash with latest Structure Block Limit thing?

### ISSUE THREAD

**Issue by Neubulae** [gnembon/fabric-carpet#738]
https://hatebin.com/yvzqiazgqa

I wonder if it's due to other mods doing the same thing or something(Tweakeroo, only present at client), could be a dummy issue.

**Comment by altrisi** [comment]
Tweakeroo did have a conflict with it, but that is already fixed in latest twekeroo builds (at least in masa's web).

Carpet TIS Addition also had one, since it did basically the same, but it has also been recently fixed in 1.13.0.

If it's not any of those, I'm not proficient enough in crash report reading yet to identify the cause.

**Comment by Neubulae** [comment]
> Tweakeroo did have a conflict with it, but that is already fixed in latest twekeroo builds (at least in masa's web).
> 
> Carpet TIS Addition also had one, since it did basically the same, but it has also been recently fixed in 1.13.0.
> 
> If it's not any of those, I'm not proficient enough in crash report reading yet to identify the cause.

Ah OK, it's dummy then. I'll close the issue.

**Comment by altrisi** [comment]
If the crash doesn't occur with Carpet but occurs with it, it's probably good to keep it open. I'm bad with convoluted crashes but someone else (like gnembon) may be able to find the cause.
