### ISSUE TITLE
/perimeterinfo can flash entities into view even if it fails with "Failed to spawn test entity" 

### ISSUE THREAD

**Issue by James103** [gnembon/fabric-carpet#761]
To reproduce:
1. Install `fabric-carpet-1.16.5-1.4.28+v210224`.
2. Launch Minecraft.
3. Create a new superflat world with cheats enabled, consisting of a single layer of glass at Y = 0.
4. Look straight down.
5. Run `/perimeterinfo ~ ~ ~ armor_stand`, optionally replacing `armor_stand` with any non-living entity.
6. `Failed to spawn test entity` is printed to chat.
7. (Actual behavior) The test entity briefly flashes into view.
(Expected behavior) The test entity does not flash into view at all.

Example screenshot:
![image](https://user-images.githubusercontent.com/37945304/110730078-7546cc00-81e5-11eb-9ef9-2f5cecaffac9.png)

**Comment by Ghoulboy78** [comment]
That is actually intended, as that is the way it is calculates. Also it is a purely visual artefact, so it isnt rly that big a deal tbh.

**Comment by gnembon** [comment]
it mimics the vanilla way of spawning entites based on the id, like /summon does. Problem is that this way you don't know the entity type until it is created using a factory method.

Could rewrite using registries and getting them from there, but I don't thing it is that necessary. An entity to spawn needs to be a mob, otherwise its little pointless. I should change the error message, cause its not true. Didn't fail to spawn a test entity, just the entity to test was pointless.

**Comment by gnembon** [comment]
btw - moving them to under the world was the way of 'removing it from view'.
