### ISSUE TITLE
Incompatible with RaisedSoundLimit Mod

### ISSUE THREAD

**Issue by QPCrummer** [gnembon/fabric-carpet#788]
Here is the mod https://github.com/ishlandbukkit/RaiseSoundLimit/
Here is my crash log https://mclo.gs/hVTpOtp
It crashed right before loading the main menu of Minecraft.

**Comment by James103** [comment]
Given the crash report, and that it mentions `carpet.mixins.json:SoundSystem_cleanLogsMixin`, the mod is likely incompatible with the `cleanLogs` carpet setting.

**Comment by QPCrummer** [comment]
I never use that option, so can I just disable it some how?

**Comment by altrisi** [comment]
Not easily though... You could remove the mixin references from the `carpet.mixins.json` file inside the mod jar, but this would need a change in Carpet in order to work properly (which I think would be either changing the priority so Carpet loads before and therefore finds the method, or making it not required).

If you want to try, you would need to open the JAR file, edit the `carpet.mixins.json` file to remove the line with `SoundSystem_cleanLogsMixin` (and maybe `SoundEngineInt_cleanLogsMixin` too) and then it should work, in theory. You would need to redo those steps after a Carpet update until that is fixed though.

**Comment by QPCrummer** [comment]
In theory, I could remove it before I compile the mod.

**Comment by QPCrummer** [comment]
I wonder if Gnembon could implement something similar RaiseSoundLimit. I don’t know how to code so I don’t really know if it would be easy or not.
