### ISSUE TITLE
Is it possible to use scarpet to increase the possibility of the wither's main head shooting blue skulls?

### ISSUE THREAD

**Issue by SpiritedAwayCN** [gnembon/fabric-carpet#825]
As the title said, I think this is useful for testing whether the wither-based farm (such as obsidian farm, wither rose farm and some kinds of tree farm) is safe enough when wither shooting blue skulls.

For vanilla, this possibility is too low to track and takes long to improve the design.

**Comment by altrisi** [comment]
I don't think with Scarpet directly (except if you emulate the entire spawning of the skull), but IIRC the `extremeBehaviours` rule affected withers somehow, although I think there were still things about those that remain untouched, since something similar was asked no long ago in the Discord (though it may have been forgotten).

**Comment by SpiritedAwayCN** [comment]
> emulate

Thank you! Then I wander if there is a way to judge blue skulls has been shot, since tick wrap makes the game too fast to see it clearly.

**Comment by Ghoulboy78** [comment]
well ig you can spawn like obsidian infront of the wither's face, and check when it's blown up like every tick, which isn't too expensive. Or you can just have an observer behind it, which triggers a command block to set the block back, tho that may get blown up aswell idk how the explosions work.

**Comment by gnembon** [comment]
https://github.com/gnembon/fabric-carpet/commit/72a3d74a975cdeaa2a47309d0f7429325e7c7f3e

not the first time its been asked for, so there it is.
