### ISSUE TITLE
-x % x returns -0, which is apparently less than and equal to 0

### ISSUE THREAD

**Issue by rv3r** [gnembon/fabric-carpet#843]
When taking the modulus of a negative number, a result that should be 0 appears to be stored as -0, which scarpet reports as being equal to 0 **_and_** less than 0. This does not happen with positive numbers.
`3 % 3 < 0 => false`
`-3 % 3 == 0 => true`
`-3 % 3 < 0 => true`
`number(-3 % 3) < 0 => false`
Though the third output is the incorrect one, it would appear that, for now, using `number()` can alleviate this in scripts. A lower level fix would be appreciated, though.

**Comment by Ghoulboy78** [comment]
lol thats funny.

**Comment by Ghoulboy78** [comment]
Ok Im confusd now the bug has stopped occurring. what?

**Comment by James103** [comment]
Does the bug reoccur if you set `/carpet scriptsOptimization false`?

**Comment by Ghoulboy78** [comment]
ok I fixed it accidentally. The problem is that in % operator it uses `NumericValue.getDouble`, which for `-3%3` returns `-0` which is a thing due to IEEE 754 standard. The fix would be to replace -0 with 0, which ought to be simple. I had managed to get the bug to disappear by using getLong, which confused me until I looked at git diff. That's the fix to this bug

**Comment by gnembon** [comment]
Fixing #842 fixes #843. I understand that the nature of #843 is deeper, but I don't believe you can obtain -0 anywhere else, and if you can - so be it - suggest fixing them on individual level, unless its not possible.

**Comment by gnembon** [comment]
https://github.com/gnembon/fabric-carpet/commit/451b35b6c5b13ecfa4f5886132794c3ee94bf2dc
